<?php
/**
 * Pre-creates new shapes and new attributes. Generated by diffShapes.php
 * The purpose of pre-creating shapes and attributes on the top few thousand networks
 * is to prevent a spike in DDL activity immediately after a release.
 * Infrequently created shapes and attributes do not need to be pre-created.
 */

// TODO: Check if title, description, and private should be indexed or not. [Jon Aquino 2008-04-09]
try { 
    $shape = XN_Shape::create('OpenSocialApp');
    $shape->setAttribute('title', array('type' => 'string', 'indexing' => 'text'));
    $shape->setAttribute('description', array('type' => 'string', 'indexing' => 'text'));
    $shape->setAttribute('private', array('type' => 'boolean', 'indexing' => 'term'));
    $shape->setAttribute('my.appUrl', array('type' => 'string'));
    $shape->setAttribute('my.avgRating', array('type' => 'number'));
    $shape->setAttribute('my.members', array('type' => 'string'));
    $shape->setAttribute('my.numMembers', array('type' => 'number'));
    $shape->setAttribute('my.numReviews', array('type' => 'number'));
    $shape->save();
} catch(Exception $e) {
    // Shape already exists
}

// TODO: Check if title, description, and private should be indexed or not. [Jon Aquino 2008-04-09]
try { 
    $shape = XN_Shape::create('OpenSocialAppData');
    $shape->setAttribute('title', array('type' => 'string', 'indexing' => 'text'));
    $shape->setAttribute('description', array('type' => 'string', 'indexing' => 'text'));
    $shape->setAttribute('private', array('type' => 'boolean', 'indexing' => 'term'));
    $shape->setAttribute('my.appUrl', array('type' => 'string'));
    $shape->setAttribute('my.canAddActivities', array('type' => 'boolean'));
    $shape->setAttribute('my.canSendMessages', array('type' => 'boolean'));
    $shape->setAttribute('my.data', array('type' => 'string'));
    $shape->setAttribute('my.installedByUrl', array('type' => 'boolean'));
    $shape->setAttribute('my.isOnMyPage', array('type' => 'boolean'));
    $shape->setAttribute('my.promptBeforeSending', array('type' => 'boolean'));
    $shape->setAttribute('my.rateLimitBlob', array('type' => 'string'));
    $shape->setAttribute('my.user', array('type' => 'string'));
    $shape->save();
} catch(Exception $e) {
    // Shape already exists
}

// TODO: Check if title, description, and private should be indexed or not. [Jon Aquino 2008-04-09]
try { 
    $shape = XN_Shape::create('OpenSocialAppReview');
    $shape->setAttribute('title', array('type' => 'string', 'indexing' => 'text'));
    $shape->setAttribute('description', array('type' => 'string', 'indexing' => 'text'));
    $shape->setAttribute('private', array('type' => 'boolean', 'indexing' => 'term'));
    $shape->setAttribute('my.appUrl', array('type' => 'string'));
    $shape->setAttribute('my.body', array('type' => 'string'));
    $shape->setAttribute('my.rating', array('type' => 'number'));
    $shape->setAttribute('my.user', array('type' => 'string'));
    $shape->save();
} catch(Exception $e) {
    // Shape already exists
}

echo 'Creates Done';
