<?php
/**
 * Pre-creates new shapes and new attributes.
 * Generated by diffShapes.php
 */

$shape = XN_Shape::load('User');
if ($shape) {
    $shape->setAttribute('my.inviter', array('type' => 'string'));
    $shape->setAttribute('my.showWelcomeBox', array('type' => 'string'));
    $shape->setAttribute('my.xg_events_eventCount', array('type' => 'number'));
    $shape->setAttribute('my.xg_events_nextEventEndDate', array('type' => 'string'));
    $shape->save();
}

echo 'Done';
